
spring:
  application:
    name: emart.api.gateway

server:
  port: 9010



eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9999/eureka/}