pipeline {
   agent any
   stages {
      stage('Build') {
         steps {
            git credentialsId: 'ibm-github', url: 'https://github.ibm.com/FSD-Works/frances-emart-mock-payment.git'
            sh 'mvn clean package -DskipTests=true'
         }
      }
      stage('Image Build'){
        steps {
          sh 'docker build . -t topgunbasten/emart-mock-payment'
        }
      }
      stage('Public Image') {
         steps {
            withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'password', usernameVariable: 'username')]) {
              sh "docker login -u ${username} -p ${password}"
              sh "docker push topgunbasten/emart-mock-payment"
            }

         }
      } 
   }
}
