
spring:
  application:
    name: emart-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${EMART_ORDER_SERVICE_DB_HOST:127.0.0.1}:${EMART_ORDER_SERVICE_DB_PORT:3306}/${EMART_ORDER_SERVICE_DB:emart_order_service_db}
    username: ${EMART_ORDER_SERVICE_USER:emart_order_service_db}
    password: ${EMART_ORDER_SERVICE_PASSWORD:Test123}
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  rabbitmq:
    host: ${QUEUE_HOST:localhost}
    port: ${QUEUE_PORT:5672}
    username: ${QUEUE_USER:guest}
    password: ${QUEUE_PASSWORD:guest}

server:
  port: 9014
  servlet:
    context-path:
      /api/v1


logback:
  access:
    enabled: true
    tomcat:
      enable-request-attributes: true
    config: "classpath:logback-access.xml"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9999/eureka/}

emart:
  rabbitmq:
    queuef: emart-queue-f
    queuei: emart-queue-i
    exchange: emart-order
    routingkey: emart.order
