spring:
  application:
    name: emart-mock_payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${EMART_MOCK_PAYMENT_DB_HOST:127.0.0.1}:${EMART_MOCK_PAYMENT_DB_PORT:3306}/${EMART_MOCK_PAYMENT_DB:emart_mock_payment_db}
    username: ${EMART_MOCK_PAYMENT_USER:emart_mock_payment_db}
    password: ${EMART_MOCK_PAYMENT_PASSWORD:Test123}
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

server:
  port: 9016
  servlet:
    context-path:
      /api/v1


logback:
  access:
    enabled: true
    tomcat:
      enable-request-attributes: true
    config: "classpath:logback-access.xml"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9999/eureka/}