spring:
  application:
    name: emart-financial-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${EMART_FINANCIAL_SERVICE_DB_HOST:127.0.0.1}:${EMART_FINANCIAL_SERVICE_DB_PORT:3306}/${EMART_FINANCIAL_SERVICE_DB:emart_financial_service_db}
    username: ${EMART_FINANCIAL_SERVICE_USER:emart_financial_service_db}
    password: ${EMART_FINANCIAL_SERVICE_PASSWORD:Test123}
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  rabbitmq:
    host: ${QUEUE_HOST:localhost}
    port: ${QUEUE_PORT:5672}
    username: ${QUEUE_USER:guest}
    password: ${QUEUE_PASSWORD:guest}

server:
  port: 9015
  servlet:
    context-path:
      /api/v1


logback:
  access:
    enabled: true
    tomcat:
      enable-request-attributes: true
    config: "classpath:logback-access.xml"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9999/eureka/}

emart:
  rabbitmq:
    queue: emart-queue
    exchange: emart-order
    routingkey: emart.order.#