

spring:
  application:
    name: eamrt-cart
  redis:
    host: ${EMART_REDIS_HOST:127.0.0.1}
    port: ${EMART_REDIS_PORT:6379}
    database: 1
    password: ${EMART_REDIS_PASSWORD:Test123}

server:
  port: 9013
  servlet:
    context-path:
      /api/v1

logback:
  access:
    enabled: true
    tomcat:
      enable-request-attributes: true
    config: "classpath:logback-access.xml"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9999/eureka/}